#!/bin/bash
# export JD reviews

# define
now=$(date +%F)
ago=$(date -d '1 day ago' +%F)
start=$(date -d $ago +%s000)
end=$(date -d $now +%s000)
query="{date:{\$gte:new Date($start),\$lt:new Date($end)}}"

# setup
PATH=/usr/local/bin:$PATH
cd "$(dirname "${BASH_SOURCE[0]}")"
dir=/var/www/jd
mkdir -p $dir
cd $dir
out=jd-review-$ago.json

if [[ -f $raw.zip || -f $out.zip ]]
then
    echo "[$(date +%FT%T)] ====== quit ======"
    exit 1
fi

# begin
echo "[$(date +%FT%T)] ====== begin ======"

# export
mongoexport -d jd -c review -q "$query" -o $out

# archive
zip $out.zip $out

# clean
rm $out
mongo jd --eval "db.review.remove($query)"

# end
echo "[$(date +%FT%T)] ====== end ======"

